spring:
  datasource:
    username: root
    password: a3181389202
    url: jdbc:mysql://localhost:3306/crud
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

tencent:
  cos:
    secretId: xxx
    secretKey: xxx
    bucketName: xxx
    region: xxx